import type { IconKey } from '../types/icon-keys.d.ts';
import { ICON_REGISTRY } from './registry.generated.ts';

export type { IconKey };

export interface IconOptions {
    /** Extra class names appended to the rendered <svg>. */
    class?: string;
    /** Optional accessible label. When set, removes aria-hidden and adds aria-label. */
    label?: string;
    /** Optional inline width (e.g. `'1em'` or `'16'`). */
    size?: string | number;
}

/**
 * Resolve an icon key to an inline SVG string. Keys are typed as `IconKey`
 * (the string-literal union generated by `scripts/gen-icons.mjs`), so a
 * misspelling fails at typecheck. Returns the raw SVG markup with
 * `currentColor` as the fill/stroke — themeable via CSS.
 *
 *   icon('fa:dice-d20', { class: 'tw-text-bronze tw-w-4 tw-h-4' })
 *
 * The icon registry is build-time generated from references in
 * `src/templates/**\/*.hbs` and `src/module/**\/*.ts`. To use a new icon:
 *
 *   1. Use it from a template `{{icon "fa:..."}}` or call `icon('fa:...')`.
 *   2. Run `pnpm icons:gen` (or commit — pre-commit regenerates).
 *   3. Typecheck picks up the new union member automatically.
 */
export function icon(key: IconKey, opts: IconOptions = {}): string {
    // Index access: TypeScript views Record<string, string> as total, but the
    // registry can drift if the typed union and the generated map fall out of
    // sync mid-build / hot-reload. Cast through unknown so the runtime guard
    // still kicks in without an unnecessary-condition lint warning.
    const svg = (ICON_REGISTRY as Record<string, string | undefined>)[key];
    if (svg === undefined || svg === '') return '';
    const classes = ['wh40k-icon', `wh40k-icon--${key.replace(':', '-')}`];
    if (opts.class !== undefined && opts.class !== '') classes.push(opts.class);
    const labelAttrs =
        opts.label !== undefined && opts.label !== '' ? `role="img" aria-label="${escapeAttr(opts.label)}"` : `aria-hidden="true" focusable="false"`;
    const sizeAttr = opts.size !== undefined ? ` style="width:${formatSize(opts.size)};height:${formatSize(opts.size)};"` : '';
    return svg.replace(/^<svg([^>]*)>/, `<svg$1 class="${classes.join(' ')}" ${labelAttrs}${sizeAttr}>`);
}

function escapeAttr(value: string): string {
    return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function formatSize(size: string | number): string {
    return typeof size === 'number' ? `${size}px` : size;
}

/**
 * True if the given key exists in the bundled registry. Mostly useful for
 * defensive runtime checks in code paths where the key is computed.
 */
export function hasIcon(key: string): key is IconKey {
    return Object.prototype.hasOwnProperty.call(ICON_REGISTRY, key);
}

/**
 * The full set of registered keys. Sorted ascending. Useful for stories /
 * dev tooling — not for production rendering.
 */
export function listIcons(): readonly IconKey[] {
    return Object.keys(ICON_REGISTRY).sort() as readonly IconKey[];
}
