// AUTO-GENERATED by scripts/gen-icons.mjs from src/templates/**/*.hbs and src/module/**/*.ts.
// Do not edit by hand. Run `pnpm icons:gen` (or commit; the pre-commit hook regenerates) to refresh.

export type IconKey = 'fa:cog' | 'fa:dice-d20' | 'lucide:dice-5' | 'lucide:settings';
