import type { I18nKey } from '../types/i18n-keys';

declare const game: {
    i18n: {
        localize: (key: string) => string;
        format: (key: string, params: Record<string, string | number | boolean>) => string;
    };
};

/**
 * Typed wrapper for `game.i18n.localize` / `game.i18n.format`. Accepts only
 * keys present in `src/lang/en.json` at build time (string-literal union
 * generated by `scripts/gen-i18n-types.mjs`). Use this instead of bare
 * `game.i18n.localize` so the type system rejects unknown keys.
 *
 *     t('WH40K.Sheet.DarkHeresy2')
 *     t('WH40K.Roll.Failure', { degrees: 2 })
 *
 * The CLAUDE.md langpack rule ("all player-facing strings live in the
 * langpack") becomes mechanical: try to ship a hard-coded English string and
 * the type system has no key for you; try to use a stale key after a langpack
 * rename and the union has no member.
 */
export function t(key: I18nKey, params?: Record<string, string | number | boolean>): string {
    if (params === undefined) return game.i18n.localize(key);
    return game.i18n.format(key, params);
}
